name: aws-codecommit-sync-reusable

on:
  workflow_call:
    inputs:
      role-to-assume:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      codecommit_url:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ${{ inputs.aws-region }}
      - name: Sync GitHub Repository to AWS CodeCommit
        uses: topotal/aws-codecommit-sync-action@0.2.2
        with:
          codecommit_url: ${{ inputs.codecommit_url }}
